apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guestbook-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: guestbook
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
